pr:
  - master

name: $(date:yyyyMMdd)$(rev:.rr)

stages:
  - stage: build
    jobs:
      - job: build_mvc
        steps:
          - script: dotnet build p2-Contagion/Contagion/Contagion.MVC/*.csproj
      - job: build_api
        steps:
          - script: dotnet build p2-Contagion/Contagion/Contagion.API/*.csproj

  # - stage: test
  #   jobs:
  #     - job: test_mvc
  #     - job: test_api
      

  - stage: analyze
    jobs:
      - job: analyze_mvc
        pool:
          vmImage: ubuntu-18.04
        steps:
          - task: DotnetGlobalToolInstaller@0
            inputs:
              name: "dotnet-sonarscanner"
          - script: |
              dotnet sonarscanner begin /k:"Contagion_mvc" /o:"Team-Contagion" /d:sonar.host.url="https://sonarcloud.io/" /d:sonar.login=$SONAR_LOGIN
              dotnet build p2-Contagion/*.sln
              dotnet sonarscanner end /d:sonar.login=$SONAR_LOGIN
            env:
              SONAR_LOGIN: $(sonar.login)
      - job: analyze_api
        pool:
          vmImage: ubuntu-18.04
        steps:
          - task: DotnetGlobalToolInstaller@0
            inputs:
              name: "dotnet-sonarscanner"
          - script: |
              dotnet sonarscanner begin /k:"Contagion_api" /o:"Team-Contagion" /d:sonar.host.url="https://sonarcloud.io/" /d:sonar.login=$SONAR_LOGIN
              dotnet build p2-Contagion/*.sln
              dotnet sonarscanner end /d:sonar.login=$SONAR_LOGIN
            env:
              SONAR_LOGIN: $(sonar.login)
  - stage: pack
    jobs:
      - job: pack_mvc
        steps:
          - task: Docker@2
            inputs:
              command: login
              containerRegistry: docker
          - script: |
              docker image build --file p2-Contagion.docker/mvc.dockerfile --tag bennetcd/mvcproj p2-Contagion/Contagion/Contagion.MVC
              docker image push bennetcd/mvcproj
          - task: Docker@2
            inputs:
              command: logout
              containerRegistry: docker
      - job: pack_api
        steps:
          - task: Docker@2
            inputs:
              command: login
              containerRegistry: docker
          - script: |
              docker image build --file p2-Contagion/api.dockerfile --tag bennetcd/apiproj p2-Contagion/Contagion/Contagion.API
              docker image push bennetcd/apiproj
          - task: Docker@2
            inputs:
              command: logout
              containerRegistry: docker

  # - stage: deploy
  #   jobs:
  #     - job: deploy_app
  #       steps:
  #         - task: DockerCompose@0
  #           displayName: Run services
  #           inputs:
  #             action: Run services
  #             azureSubscriptionEndpoint: $(azure.subscription)
  #             containerRegistryType: Container Registry
  #             dockerComposeFile: docker-compose.yaml
  #             projectName: $(Build.Repository.Name)
  #             buildImages: false
  #             detached: false

trigger:
  - master